### ISSUE TITLE
вот

### ISSUE THREAD

**Issue by Yura64UA** [erickskrauch/da-pizda-telegram-bot#15]
```
Да́
```
и
```
Да
Да
```

**Comment by Yura64UA** [comment]
с 𐌀 игнорирует

**Comment by Yura64UA** [comment]
```
ДА̀
```
https://en.wikipedia.org/wiki/A_with_grave_(Cyrillic)

**Comment by Yura64UA** [comment]
```
да̂
```
https://en.wikipedia.org/wiki/A_with_circumflex_(Cyrillic)

**Comment by Yura64UA** [comment]
```
да̄
```
https://en.wikipedia.org/wiki/A_with_macron_(Cyrillic)

**Comment by Yura64UA** [comment]
```
Ꙣа
```
https://en.wiktionary.org/wiki/%EA%99%A2

**Comment by Yura64UA** [comment]
```
д҄а
```
https://uk.wikipedia.org/wiki/%D0%9F%D0%BE%D1%80%D1%96%D0%B2%D0%BD%D1%8F%D0%BD%D0%BD%D1%8F_%D0%BF%D1%80%D0%B0%D0%B2%D0%BE%D0%BF%D0%B8%D1%81%D1%96%D0%B2_%D1%83%D0%BA%D1%80%D0%B0%D1%97%D0%BD%D1%81%D1%8C%D0%BA%D0%BE%D1%97_%D0%BC%D0%BE%D0%B2%D0%B8

**Comment by Yura64UA** [comment]
```
дѧ
```
https://ru.wikipedia.org/wiki/%D0%AE%D1%81_%D0%BC%D0%B0%D0%BB%D1%8B%D0%B9

**Comment by Yura64UA** [comment]
```
дꙗ
```
https://ru.wikipedia.org/wiki/%D0%90_%D0%B9%D0%BE%D1%82%D0%B8%D1%80%D0%BE%D0%B2%D0%B0%D0%BD%D0%BD%D0%BE%D0%B5

**Comment by erickskrauch** [comment]
@Yura64UA, я не уверен, что `ꙗ` является буквой а. Она буквально называется "а йотированное" и звучит как "я".
