### ISSUE TITLE
ппизда

### ISSUE THREAD

**Issue by Yura64UA** [erickskrauch/da-pizda-telegram-bot#18]
Ввод:
```
д̌ӓ̄
```
https://en.wikipedia.org/wiki/De_with_caron
https://en.wikipedia.org/wiki/A_with_diaeresis_and_macron_(Cyrillic)
Вывод:
```
ппиздӓ̄
```

**Comment by Yura64UA** [comment]
![зображення](https://github.com/erickskrauch/da-pizda-bot/assets/96763383/164dadc9-90d0-4c46-8fc6-30384b061f0b)
```
д̆а
```

**Comment by erickskrauch** [comment]
Дело в том, что библиотека для работы с utf8 строками не умеет в составные символы и определяет части диакрита как 2 символа. Смотрю, что с этим можно сделать.

**Comment by Yura64UA** [comment]
понял

**Comment by Yura64UA** [comment]
![зображення](https://github.com/erickskrauch/da-pizda-bot/assets/96763383/a0e73991-6707-4b1c-8d21-98900f0bb903)
вот ещё подобное

**Comment by erickskrauch** [comment]
Да, там из-за неправильного вычисления длины строки плывёт вычисление подстрок. Я составляю issue в используемую библиотеку. Вечно они понаделают поддержки латиницы, а про кирилические символы и не думают.
