### ISSUE TITLE
Добавьте ответ на слово «нет»

### ISSUE THREAD

**Issue by alexsovi** [erickskrauch/da-pizda-telegram-bot#20]
Если человек напишет «нет», то бот ответит «разъебу тебе еблет» или «пидора ответ»

**Comment by erickskrauch** [comment]
Нет, (~~пидора ответ~~) к сожалению, этот бот не будет поддерживать никакие другие сообщения и ответы на них. Он создан, чтобы выполнять лишь 1 задачу. И он будет выполнять её хорошо. Лицензия бота допускает любое его использование, так что вы можете форкнуть его и сделать свою комбинацию триггера и ответа :)
