### ISSUE TITLE
Please add additional reply

### ISSUE THREAD

**Issue by andsol** [erickskrauch/da-pizda-telegram-bot#24]
Would be nice to have proper answer for "300"

**Comment by erickskrauch** [comment]
Нет (пидора ответ). Этот бот создан для того, чтобы выполнять лишь одну задачу. И он выполняет её хорошо. Вы всегда можете сделать форк репозитория и заточить его под свои нужды. Я даже с радостью добавлю ссылку в README, указывающую на вашего бота, чтобы любой желающий мог собрать полную коллекцию ботов на своём канале :)
