### ISSUE TITLE
Вопрос

### ISSUE THREAD

**Issue by NORTCHOT** [erickskrauch/da-pizda-telegram-bot#25]
для переделки бота можно работать только с папкой src? не шарю и никогда не шарил в дискорд ботах, а тем более в тайпскрипте

**Comment by erickskrauch** [comment]
Нет, можно располагать файлы где угодно. Следует только добавить их в `include` секцию tsconfig: https://github.com/erickskrauch/da-pizda-bot/blob/4b50919842dbbde8bc7e400641410bd96c28601e/tsconfig.json#L2.
