### ISSUE TITLE
Поддержка сторонних сервисов

### ISSUE THREAD

**Issue by turikhay** [erickskrauch/da-pizda-telegram-bot#4]
В чате часто спрашивают о расширении поддержки на другие сервисы, где есть чат. Предлагаемые:

- [ ] Twitch
- [ ] Discord
- [ ] Slack
- [ ] Госуслуги

**Comment by erickskrauch** [comment]
Я создал отдельное issue для Discord: https://github.com/erickskrauch/da-pizda-telegram-bot/issues/13. Остальные сервисы не вижу большого смысла поддерживать. Но если будут ещё спрашивать, то сделаю.
