### ISSUE TITLE
Очень важные кейсы

### ISSUE THREAD

**Issue by Nik-mmzd** [erickskrauch/da-pizda-telegram-bot#5]
`Ｄａ`
`🅓🅐`
`ᗪ卂`
`🅳🅰`
`𝐝𝐚`
`𝖉𝖆`
`ⓓⓐ`
`𝓭𝓪`
`𝙙𝙖`

**Comment by Apceniy** [comment]
также не реагирует на данные кейсы:
`дæ`
`дα`
`δа`
`ðа`

а также теряет диакриты у буквы "d"

**Comment by Nik-mmzd** [comment]
А давайте упоремся? Будем проверять буквы по их названию в юникоде :D

**Comment by erickskrauch** [comment]
@Apceniy, кейсы с деакритами для буквы d слеует описать в отдельном issue. Если сможешь, выпиши, пожалуйста.

**Comment by erickskrauch** [comment]
Также надо бы не потерять эту ссылку.
https://gist.github.com/StevenACoffman/a5f6f682d94e38ed804182dc2693ed4b
