### ISSUE TITLE
"No - choice" functional enhancement

### ISSUE THREAD

**Issue by GrinColdWright** [erickskrauch/da-pizda-telegram-bot#8]
Бот работает только с переменной "Да", что отражает ожидаемый результат. Но сторона клиента также предложила ввести альтернативу с вариантом "Нет". 

Ожидаемый результат: бот выводит на реплику "Нет" фразу "Пидора ответ". 

На переменную "Нет" должны работать те же параметры что и на переменную "Да" : Вариации шрифта, пробелы, сохранение пунктуации при записях ("Нет!" "Нет." "Нет?" и т.п.).  Решение введения функционала в виде отдельного проекта остается за командой разработки.

**Comment by erickskrauch** [comment]
Бот спроектирован делать лишь одну вещь: на каждое "да" незамедлительно отвечать "пизда". И он спроектирован делать её хорошо :) Все остальные реакции будут лишь отдалять бот от его предназначения и увеличивать количество шума, создаваемое им в группах. Поэтому я остановлюсь на том, что бот будет обрабатывать только "да".
